# Site settings
title: Yet Another Blog
email: talk@nkt.me
description: ~
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gusnkt
github_username:  nkt

# Build settings
markdown: kramdown
